export const SET_VIDEOGAMES = 'SET_VIDEOGAMES'
export const SEARCH = 'SEARCH'
export const ALL = 'ALL'
export const ORDENALF = 'ORDENALF'
export const RATING = 'RATING'
export const FILTERID = 'FILTERID'
export const FILTERGEN = 'FILTERGEN'
